
version: "3.8"
services:
  biogpt:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"